services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habit-tracker-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-1.c7gcs0s62u44.us-east-2.rds.amazonaws.com:5432/habittracker
      SPRING_DATASOURCE_USERNAME: habituser
      SPRING_DATASOURCE_PASSWORD: habitpass
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habit-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
